<a href="https://colab.research.google.com/github/Karthik5412/Deep-Learning-Projects/blob/main/ANN%20Model/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/content/zomato.csv', engine= 'python', on_bad_lines='skip')

df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [5]:
print(df.shape)
df.isna().sum()

(13180, 17)

url                               0
address                           0
name                              0
online_order                      0
book_table                        0
rate                           1910
votes                             0
phone                           275
location                          2
rest_type                        56
dish_liked                     7272
cuisines                         10
approx_cost(for two people)      35
reviews_list                      0
menu_item                         0
listed_in(type)                   0
listed_in(city)                   0
dtype: int64

In [6]:
df = df.dropna()
df.isna().sum()

url                            0
address                        0
name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
reviews_list                   0
menu_item                      0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [7]:
print(df.columns)
unwanted_cols = ['menu_item','phone']

df= df.drop(columns=unwanted_cols)

df.head(2)

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

,url,address,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",Buffet,Banashankari

In [8]:
df['total address'] = df['address'] + ', ' +df['location'] + ', ' +  df['listed_in(city)']
df['food items'] = df['dish_liked'] + ', ' +df['cuisines']
original_df = df.copy()

df = df[['listed_in(type)','rest_type','total address','book_table','online_order', 'rate', 'approx_cost(for two people)']]
df.head(2)

,listed_in(type),rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,Casual Dining,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,800
1,Buffet,Casual Dining,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",No,Yes,4.1/5,800

In [9]:
df.to_csv('cleaned_df.csv')

In [10]:
from nltk.tag.brill import Word
import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lematizer = WordNetLemmatizer()

def preprocessing_data (text) -> str:

    text = str(text)
    # Converting the text into lower case
    text = text.lower()

    # Removing punctuvations
    text = re.sub(r'[^a-zA-Z0-9\s]','',text)

    # Removing stop words
    words = [w for w in text.split() if w not in stop_words]

    # Lemotization
    words = [lematizer.lemmatize(w) for w in words]

    return ' '.join(words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [11]:
df['total address'] = ' - ' + df['total address']
df['total address'] = df['total address'].apply(preprocessing_data)
df.head(2)

,listed_in(type),rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,Casual Dining,942 21st main road 2nd stage banashankari bang...,Yes,Yes,4.1/5,800
1,Buffet,Casual Dining,2nd floor 80 foot road near big bazaar 6th blo...,No,Yes,4.1/5,800

In [12]:
df.loc[df['rate'] == 'NEW','rate'] = df['rate'].mode()[0]
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '4.6/5', '4.0/5', '4.2/5', '3.9/5',
       '3.0/5', '3.6/5', '2.8/5', '4.4/5', '3.1/5', '4.3/5', '2.6/5',
       '3.3/5', '3.5/5', '3.8 /5', '3.2/5', '4.5/5', '2.5/5', '2.9/5',
       '3.4/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5', '4.8/5',
       '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5', '2.7 /5',
       '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5', '4.4 /5',
       '4.9/5', '2.1/5', '2.0/5', '1.8/5', '3.4 /5', '3.6 /5', '3.3 /5',
       '4.6 /5', '4.9 /5', '3.2 /5', '3.0 /5'], dtype=object)

In [13]:
df['rate'] = df['rate'].apply(lambda x: x.replace('/5','')).str.strip().astype('float')
df['book_table'] = df['book_table'].map({'Yes': 1, 'No': 0}).astype('int')
df['online_order'] = df['online_order'].map({'Yes': 1, 'No': 0}).astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5828 entries, 0 to 13179
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   listed_in(type)              5828 non-null   object
 1   rest_type                    5828 non-null   object
 2   total address                5828 non-null   object
 3   book_table                   5828 non-null   int64
 4   online_order                 5828 non-null   int64
 5   rate                         5828 non-null   float64
 6   approx_cost(for two people)  5828 non-null   object
dtypes: float64(1), int64(2), object(4)
memory usage: 364.2+ KB

In [14]:
df.head(2)

,listed_in(type),rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,Casual Dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800
1,Buffet,Casual Dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800

In [15]:
df['rest_type'] = df['rest_type'].apply(preprocessing_data)

df.head(2)

,listed_in(type),rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,casual dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800
1,Buffet,casual dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800

In [29]:
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].apply(lambda x: x.replace(',', '')).astype(float)

In [16]:
df['listed_in(type)'] = df['listed_in(type)'].replace('Drinks & nightlife' , 'Drinks and Nightlife')
df['listed_in(type)'].unique()

array(['Buffet', 'Cafes', 'Delivery', 'Desserts', 'Dine-out',
       'Drinks and Nightlife', 'Pubs and bars'], dtype=object)

In [17]:
df.head()

,listed_in(type),rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,Buffet,casual dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800
1,Buffet,casual dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800
2,Buffet,cafe casual dining,1112 next kims medical college 17th cross 2nd ...,0,1,3.8,800
3,Buffet,quick bite,1st floor annakuteera 3rd stage banashankari b...,0,0,3.7,300
4,Buffet,casual dining,10 3rd floor lakshmi associate gandhi bazaar m...,0,0,3.8,600

In [18]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

In [19]:
df['listed_in(type)'] = label_encoder.fit_transform(df['listed_in(type)'])
df.head(2)

,listed_in(type),rest_type,total address,book_table,online_order,rate,approx_cost(for two people)
0,0,casual dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800
1,0,casual dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800

In [20]:
df['final_phrase'] = df['rest_type'] + ' ' + df['total address']

df.head(2)

,listed_in(type),rest_type,total address,book_table,online_order,rate,approx_cost(for two people),final_phrase
0,0,casual dining,942 21st main road 2nd stage banashankari bang...,1,1,4.1,800,casual dining 942 21st main road 2nd stage ban...
1,0,casual dining,2nd floor 80 foot road near big bazaar 6th blo...,0,1,4.1,800,casual dining 2nd floor 80 foot road near big ...

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features= 1000)

tfidf_matrix = tfidf.fit_transform(df['final_phrase']).toarray()

In [32]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

cost_matrix = scaler.fit_transform(df.drop(columns= ['rest_type', 'total address','final_phrase']))

In [35]:
final_matrix = np.hstack((tfidf_matrix, cost_matrix))

final_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.63268343,
         0.50100059,  0.09754685],
       [ 0.        ,  0.        ,  0.        , ...,  0.63268343,
         0.50100059,  0.09754685],
       [ 0.        ,  0.        ,  0.        , ...,  0.63268343,
        -0.18205418,  0.09754685],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -1.58056929,
         0.95637044,  1.05189138],
       [ 0.        ,  0.        ,  0.        , ..., -1.58056929,
         0.72868552,  1.43362919],
       [ 0.        ,  0.        ,  0.        , ..., -1.58056929,
         1.18405536,  0.47928466]])